package com.triporg.repository;

import com.triporg.entity.Expense;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface ExpenseRepository extends JpaRepository<Expense, String> {
    List<Expense> findByTripIdOrderByCreatedAtDesc(String tripId);
    
    @Query("SELECT e FROM Expense e WHERE e.trip.id = :tripId AND e.isShared = true")
    List<Expense> findSharedByTripId(@Param("tripId") String tripId);
    
    @Query("SELECT e FROM Expense e WHERE e.trip.id = :tripId AND e.isAutoGenerated = true AND e.autoSource = :autoSource")
    java.util.Optional<Expense> findAutoGeneratedByTripAndSource(@Param("tripId") String tripId, @Param("autoSource") String autoSource);
    
    @Query("SELECT e FROM Expense e WHERE e.trip.id = :tripId AND e.isAutoGenerated = true")
    List<Expense> findAutoGeneratedByTripId(@Param("tripId") String tripId);
}


